name: CI
env: { STAGE_PORT: 8081, CONTAINER_PORT: 8080 }
on:
  workflow_dispatch:
  push:
jobs:
  server-test:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Get the code
        uses: actions/checkout@v4
      - name: âš™ï¸ Load & Cache Dependencies
        uses: ./.github/actions/cached-deps
        with:
          prefix: .
          caching: "false"
      - name: ğŸ§ª Test Render Service
        run: npm run test-render:ci
      - name: ğŸ§ª Test Auth Service
        run: npm run test-auth:ci
      - name: ğŸ§ª Test Common Service
        run: npm run test-common:ci
  dockerize:
    needs: [server-test]
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: toor
    env:
      MONGODB_CLUSTER_ADDRESS: 127.0.0.1:27017 # mongodb, if ports not mentioned
    steps:
      - name: â¬‡ï¸ Get the code
        uses: actions/checkout@v4
      - name: ğŸŸ Build stage image
        run: docker build -f Dockerfile.prod -t "${{ secrets.WF_DOCKER_STAGE_IMAGE_NAME }}" . --build-arg MONGO_URI="${{ env.MONGODB_CLUSTER_ADDRESS }}" --build-arg NODE_ENV="production" --build-arg DATABASE="${{ secrets.WF_MONGODB_STAGE_DATABASE_NAME }}" --build-arg ADMIN_PASSWORD="${{ secrets.WF_ADMIN_PASSWORD_STAGE }}"
      - name: ğŸ¡ Run stage image
        run: docker run -d -p ${{ env.STAGE_PORT }}:${{ env.CONTAINER_PORT }} ${{ secrets.WF_DOCKER_STAGE_IMAGE_NAME }}
      - name: ğŸ’¤ Sleep for 30 seconds
        run: sleep 30
      - name: ğŸ“ Calling stage api
        run: curl http://localhost:${{ env.STAGE_PORT }}/api/currentuser
      - name: ğŸ’¬ Sending Notification
        uses: stegzilla/discord-notify@v4
        with:
          title: dockerize
          include_image: true
          username: ${{ github.actor }}
          message: âœ… Working!, Now Stage This ğŸ‘‰ Link!!!
          webhook_url: ${{ secrets.WF_DISCORD_WEBHOOK_URL }}
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
